Repository Kaaveh/ComposeNews, pull requests merged in 2023-10, with the labels that each got.

#117 [bugfix] crash on master branch
  app/src/main/java/ir/composenews/navigation/ComposeNewsNavHost.kt
  app/src/main/java/ir/composenews/ui/ComposeNewsApp.kt
  app/src/main/java/ir/composenews/ui/MainActivity.kt
  app/src/main/java/ir/composenews/ui/MainViewModel.kt
  core/base/src/main/java/ir/composenews/base/MainContract.kt
  feature/marketlist/src/main/java/ir/composenews/marketlist/MarketListScreen.kt
  library/navigation/src/main/java/ir/composenews/navigation/MainContract.kt
  library/navigation/src/main/java/ir/composenews/navigation/graph/FavoriteNews.kt
  library/navigation/src/main/java/ir/composenews/navigation/graph/NewsDetail.kt
  library/navigation/src/main/java/ir/composenews/navigation/graph/NewsList.kt
Labels: bug

#120 Update README.md
  README.md
Labels: documentation

#118 Enhacement/empty state in favorite screen
  feature/marketlist/src/main/java/ir/composenews/marketlist/MarketListContract.kt
  feature/marketlist/src/main/java/ir/composenews/marketlist/MarketListScreen.kt
  feature/marketlist/src/main/java/ir/composenews/marketlist/MarketListViewModel.kt
  gradle/libs.versions.toml
  library/designsystem/build.gradle.kts
  library/designsystem/src/main/java/ir/composenews/designsystem/component/EmptyStateAnimation.kt
  library/designsystem/src/main/java/ir/composenews/designsystem/component/LottieAnimationComposable.kt
  library/designsystem/src/main/res/raw/empty_state_animation.json
Labels: enhancement, hacktoberfest

#122 Update README.md
  README.md
Labels: documentation

#121 Fix gradle warnings
  app/build.gradle.kts
  build-logic/convention/src/main/kotlin/AndroidKotlinterConventionPlugin.kt
  build-logic/convention/src/main/kotlin/ir/composenews/Kotliner.kt
  build.gradle.kts
Labels: enhancement

#127 [Clean up]: Remove unused files
  core/base/consumer-rules.pro
  core/base/proguard-rules.pro
  core/sync/consumer-rules.pro
  core/sync/proguard-rules.pro
  core/test/consumer-rules.pro
  core/test/proguard-rules.pro
  core/uimarket/consumer-rules.pro
  core/uimarket/proguard-rules.pro
  data/market-local/consumer-rules.pro
  data/market-local/proguard-rules.pro
  data/market-remote/consumer-rules.pro
  data/market-remote/proguard-rules.pro
  data/market-repository/consumer-rules.pro
  data/market-repository/proguard-rules.pro
  domain/market/consumer-rules.pro
  domain/market/proguard-rules.pro
  feature/marketdetail/consumer-rules.pro
  feature/marketdetail/proguard-rules.pro
  feature/marketlist/consumer-rules.pro
  feature/marketlist/proguard-rules.pro
  library/designsystem/proguard-rules.pro
  library/navigation/consumer-rules.pro
  library/navigation/proguard-rules.pro
Labels: enhancement

#130 Update README.md
  README.md
Labels: documentation

#137 Refactor/update dependencies
  gradle/libs.versions.toml
Labels: enhancement

#138 [ui] add new app icon
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: enhancement

#140 Refactor/convention plugins
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/AndroidApplicationComposeConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidDetektConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidHiltConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidKotlinterConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidLibraryComposeConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidLibraryConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidRoomConventionPlugin.kt
  build-logic/convention/src/main/kotlin/HiltConventionPlugin.kt
  build-logic/convention/src/main/kotlin/RoomConventionPlugin.kt
  build-logic/convention/src/main/kotlin/ir/composenews/Compose.kt
  build-logic/convention/src/main/kotlin/ir/composenews/Detekt.kt
  build-logic/convention/src/main/kotlin/ir/composenews/KotlinAndroid.kt
  build-logic/convention/src/main/kotlin/ir/composenews/ProjectExtensions.kt
Labels: enhancement

#139 feat: Implemented Continuous Integration(CI) pipeline for automated/manual build workflow
  .github/workflows/ci.yaml
  .github/workflows/dependabot.yml
Labels: enhancement

#143 Doc/update readme
  README.md
  asset/IMG_2412.jpeg
Labels: documentation

#148 Optimize/round decimal number
  core/extensions/.gitignore
  core/extensions/build.gradle.kts
  core/extensions/src/main/AndroidManifest.xml
  core/extensions/src/main/java/ir/composenews/extensions/Number.kt
  core/extensions/src/test/java/ir/composenews/extensions/RoundToTwoDecimalPlacesTest.kt
  feature/marketlist/build.gradle.kts
  feature/marketlist/src/main/java/ir/composenews/marketlist/component/MarketListItem.kt
  settings.gradle
Labels: enhancement, hacktoberfest

#153 Optimize/hilt scope
  core/test/src/main/java/ir/composenews/core_test/dispatcher/DispatcherProvider.kt
  data/market-local/src/main/java/ir/composenews/localdatasource/di/LocalDatasourceModule.kt
  data/market-remote/src/main/java/ir/composenews/remotedatasource/di/RemoteDatasourceModule.kt
  library/designsystem/src/main/java/ir/composenews/designsystem/component/DismissBackgroundSwipe.kt
  library/designsystem/src/main/java/ir/composenews/designsystem/component/EmptyStateAnimation.kt
  library/designsystem/src/main/java/ir/composenews/designsystem/theme/Color.kt
  library/designsystem/src/main/java/ir/composenews/designsystem/theme/Theme.kt
  library/designsystem/src/main/java/ir/composenews/utils/WindowStateUtils.kt
  library/navigation/src/main/java/ir/composenews/navigation/extension_function/Bundle.kt
Labels: enhancement

#154 Doc/update readme
  README.md
  asset/IMG_2459.jpeg
  asset/arch.jpg
  asset/architecture.jpg
  asset/dark_mode.jpg
  asset/header.jpeg
  asset/light_mode.jpg
Labels: documentation

#158 optimize performanse
  app/src/main/java/ir/composenews/navigation/ComposeNewsNavHost.kt
  app/src/main/java/ir/composenews/ui/ComposeNewsApp.kt
  app/src/main/java/ir/composenews/ui/MainActivity.kt
  app/src/main/java/ir/composenews/ui/component/BottomNavigationBar.kt
  app/src/main/java/ir/composenews/ui/component/NavigationRail.kt
  domain/market/src/main/java/ir/composenews/domain/use_case/GetMarketListUseCase.kt
  feature/marketlist/src/main/java/ir/composenews/marketlist/MarketListScreen.kt
  feature/marketlist/src/main/java/ir/composenews/marketlist/MarketListViewModel.kt
  library/navigation/src/main/java/ir/composenews/navigation/graph/FavoriteNews.kt
  library/navigation/src/main/java/ir/composenews/navigation/graph/NewsList.kt
Labels: enhancement

#159 Bugfix/ci
  .github/workflows/ci.yaml
  .github/workflows/dependabot.yml
  feature/marketlist/src/main/java/ir/composenews/marketlist/MarketListScreen.kt
  feature/marketlist/src/main/java/ir/composenews/marketlist/MarketListViewModel.kt
  feature/marketlist/src/test/java/ir/composenews/marketlist/MarketListViewModelTest.kt
Labels: bug

#163 [refactor] update dependencies
  gradle/libs.versions.toml
Labels: enhancement

#164 Optimize/price change colors in market list
  library/designsystem/src/main/java/ir/composenews/designsystem/component/MarketItem.kt
  library/designsystem/src/main/java/ir/composenews/designsystem/theme/Color.kt
Labels: enhancement, hacktoberfest-accepted

#168 Update theme headers
  README.md
Labels: documentation

#171 update version branch
  README.md
Labels: documentation

#170 [version] 1.0.0
  README.md
  asset/tablet_view.jpg
  gradle/libs.versions.toml
Labels: release
