Repository Kaaveh/ComposeNews, pull requests merged in 2024-09, with the labels that each got.

#219 Enhance/error handling
  core/base/build.gradle.kts
  core/base/src/main/java/ir/composenews/base/BaseContract.kt
  core/base/src/main/java/ir/composenews/base/BaseScreen.kt
  core/network/ktor/.gitignore
  core/network/ktor/build.gradle.kts
  core/network/ktor/src/main/java/ir/composenews/network/ApiResponse.kt
  core/network/ktor/src/main/java/ir/composenews/network/ApiResponseExtension.kt
  core/network/ktor/src/main/java/ir/composenews/network/ErrorMapper.kt
  core/network/ktor/src/main/java/ir/composenews/network/Errors.kt
  core/network/ktor/src/main/java/ir/composenews/network/HttpClientExtension.kt
  core/network/ktor/src/main/java/ir/composenews/network/Resource.kt
  core/network/ktor/src/main/java/ir/composenews/network/ResponseTransformer.kt
  core/network/ktor/src/main/java/ir/composenews/network/StatusCode.kt
  data/market-remote/build.gradle.kts
  data/market-remote/src/main/java/ir/composenews/remotedatasource/api/MarketsApi.kt
  data/market-remote/src/main/java/ir/composenews/remotedatasource/api/MarketsApiImpl.kt
  data/market-remote/src/main/java/ir/composenews/remotedatasource/test/FakeMarketsApi.kt
  data/market-repository/src/main/java/ir/composenews/data/repository/MarketRepositoryImpl.kt
  domain/market/build.gradle.kts
  domain/market/src/main/java/ir/composenews/domain/model/Resource.kt
  domain/market/src/main/java/ir/composenews/domain/repository/MarketRepository.kt
  domain/market/src/main/java/ir/composenews/domain/use_case/GetMarketChartUseCase.kt
  domain/market/src/main/java/ir/composenews/domain/use_case/GetMarketDetailUseCase.kt
  feature/marketdetail/src/androidTest/java/ir/composenews/marketdetail/MarketDetailScreenTest.kt
  feature/marketdetail/src/main/java/ir/composenews/marketdetail/MarketDetailViewModel.kt
  feature/marketdetail/src/test/java/ir/composenews/marketdetail/MarketDetailViewModelTest.kt
  feature/marketlist/src/main/java/ir/composenews/marketlist/MarketListViewModel.kt
  gradle/libs.versions.toml
  settings.gradle
Labels: enhancement

#221 Update Project Dependencies and Fix Breaking Changes
  .github/workflows/build.yml
  app/build.gradle.kts
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidLibraryComposeConventionPlugin.kt
  build-logic/convention/src/main/kotlin/HiltConventionPlugin.kt
  build-logic/convention/src/main/kotlin/ir/composenews/Compose.kt
  build-logic/convention/src/main/kotlin/ir/composenews/KotlinAndroid.kt
  build-logic/convention/src/main/kotlin/ir/composenews/ProjectExtensions.kt
  build.gradle.kts
  core/network/ktor/src/main/java/ir/composenews/network/ApiResponseExtension.kt
  core/network/ktor/src/main/java/ir/composenews/network/StatusCode.kt
  data/market-local/build.gradle.kts
  data/market-local/src/main/java/ir/composenews/localdatasource/di/LocalDatasourceModule.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  library/designsystem/src/main/java/ir/composenews/designsystem/component/MarketItem.kt
Labels: enhancement

#225 debug/build_issue
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  library/designsystem/src/main/java/ir/composenews/designsystem/component/MarketItem.kt
Labels: bug

#226 Add Konsist Library for Code Consistency and Update AGP to Prevent R8 Build Issue
  gradle/libs.versions.toml
  konsist/.gitignore
  konsist/build.gradle.kts
  konsist/src/test/java/ir/composenews/konsist/KonsistUseCaseTest.kt
  settings.gradle
Labels: enhancement

#218 WearOS version
  .kotlin/sessions/kotlin-compiler-13236832659117465399.salive
  README.md
  app-watch/app/.gitignore
  app-watch/app/build.gradle.kts
  app-watch/app/lint.xml
  app-watch/app/proguard-rules.pro
  app-watch/app/src/androidTest/java/ir/composenews/ui/MainActivityTest.kt
  app-watch/app/src/main/AndroidManifest.xml
  app-watch/app/src/main/java/ir/composenews/ComposeNewsWearApplication.kt
  app-watch/app/src/main/java/ir/composenews/MainViewModel.kt
  app-watch/app/src/main/java/ir/composenews/navigation/ComposeNewsWearNavHost.kt
  app-watch/app/src/main/java/ir/composenews/ui/MainActivity.kt
  app-watch/app/src/main/res/values/strings.xml
  app-watch/designsystem/.gitignore
  app-watch/designsystem/build.gradle.kts
  app-watch/designsystem/src/main/AndroidManifest.xml
  app-watch/designsystem/src/main/java/ir/composenews/appwatch/designsystem/theme/Theme.kt
  app-watch/designsystem/src/main/res/values/dimens.xml
  app-watch/navigation/.gitignore
  app-watch/navigation/build.gradle.kts
  app-watch/navigation/src/main/AndroidManifest.xml
  app-watch/navigation/src/main/java/ir/composenews/appwatch/navigation/graph/Destinations.kt
  app-watch/navigation/src/main/java/ir/composenews/appwatch/navigation/graph/MainContract.kt
  app-watch/navigation/src/main/java/ir/composenews/appwatch/navigation/graph/NewsDetail.kt
  app-watch/navigation/src/main/java/ir/composenews/appwatch/navigation/graph/NewsList.kt
  app-watch/ui/.gitignore
  app-watch/ui/build.gradle.kts
  app-watch/ui/src/main/AndroidManifest.xml
  app-watch/ui/src/main/java/ir/composenews/appwatch/ui/details/MarketWearDetails.kt
  app-watch/ui/src/main/java/ir/composenews/appwatch/ui/list/MarketItem.kt
  app-watch/ui/src/main/java/ir/composenews/appwatch/ui/list/MarketListWearScreen.kt
  asset/wearos.jpg
  gradle/libs.versions.toml
  library/designsystem/src/main/java/ir/composenews/designsystem/component/QuadLineChart.kt
  library/designsystem/src/main/res/values/dimens.xml
  settings.gradle
Labels: enhancement

#229 [#228] update readme diagram
  README.md
  asset/arch.jpg
  asset/architecture.jpg
Labels: documentation

#231 [refactor] #230 WearOS version
  .kotlin/sessions/kotlin-compiler-13236832659117465399.salive
  README.md
  app-watch/app/build.gradle.kts
  app-watch/app/src/main/java/ir/composenews/ComposeNewsWearApplication.kt
  app-watch/app/src/main/java/ir/composenews/MainViewModel.kt
  app-watch/app/src/main/java/ir/composenews/navigation/ComposeNewsWearNavHost.kt
  app-watch/app/src/main/java/ir/composenews/ui/MainActivity.kt
  app-watch/designsystem/.gitignore
  app-watch/designsystem/build.gradle.kts
  app-watch/designsystem/src/main/AndroidManifest.xml
  app-watch/designsystem/src/main/java/ir/composenews/appwatch/designsystem/theme/Theme.kt
  app-watch/designsystem/src/main/res/values/dimens.xml
  app-watch/navigation/build.gradle.kts
  app-watch/navigation/src/main/java/ir/composenews/appwatch/navigation/MainContract.kt
  app-watch/navigation/src/main/java/ir/composenews/appwatch/navigation/graph/MarketDetail.kt
  app-watch/navigation/src/main/java/ir/composenews/appwatch/navigation/graph/MarketList.kt
  app-watch/ui/build.gradle.kts
  app-watch/ui/src/main/java/ir/composenews/appwatch/ui/list/MarketItem.kt
  app/build.gradle.kts
  asset/arch.jpg
  asset/architecture.jpg
  build-logic/convention/build.gradle.kts
  core/base/build.gradle.kts
  core/uimarket/build.gradle.kts
  data/market-remote/build.gradle.kts
  domain/market/build.gradle.kts
  feature/marketdetail/build.gradle.kts
  feature/marketlist/build.gradle.kts
  konsist/build.gradle.kts
  library/navigation/src/main/java/ir/composenews/navigation/graph/FavoriteMarketList.kt
  library/navigation/src/main/java/ir/composenews/navigation/graph/MarketDetail.kt
  library/navigation/src/main/java/ir/composenews/navigation/graph/MarketList.kt
  settings.gradle
Labels: refactor

#233 Only run Danger checks on PRs from the same repository
  .github/workflows/danger_checks.yml
Labels: bug
